#! /usr/bin/env python3
"""ImmoBit Daemon."""

from immobit.config import CONFIG
from immobit.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
