#! /usr/bin/env python3
"""ImmoBit Daemon."""

from his.config import CONFIG
from immobit.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['immobit']['host']
    PORT = int(CONFIG['immobit']['port'])
    APPLICATION.run(host=HOST, port=PORT)
